# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=mantle
mod_version=1.12

# Minecraft Version Information
minecraft_version=1.21.1
minecraft_range=[1.21.1]

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Neo
loader_range=[1,)
neo_version=21.1.144
neo_range=[21.1.144,)

# Build dependencies
jei_version=19.51.0.418
jei_range=[19.51.0.418,)
