# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

mod_version=1.12

# Minecraft Version Information
minecraft_version=1.21.1
minecraft_range=[1.21.1,1.21.2)

# NeoForge Version Information
loader_range=[4,)
neo_version=21.1.228
neo_range=[21.1.228,)

# Build dependencies
jei_version=19.27.0.340
