@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.mantle.inventory;

import mcp.MethodsReturnNonnullByDefault;

import org.jetbrains.annotations.ParametersAreNonnullByDefault;
