@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.mantle.registration;

import mcp.MethodsReturnNonnullByDefault;

import org.jetbrains.annotations.ParametersAreNonnullByDefault;
