@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.mantle.registration.deferred;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
