@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.mantle.registration.deferred;

import mcp.MethodsReturnNonnullByDefault;

import org.jetbrains.annotations.ParametersAreNonnullByDefault;
