@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.mantle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
