@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.mantle.registration.object;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
